import type { CharacterConfig } from "@/lib/game/types";

export const CHARACTERS: CharacterConfig[] = [
  {
    id: "wizard",
    name: "wizard",
    displayName: "Archmage Zephyr",
    description:
      "An ancient spellcaster who weaves reality with syllables and sigils.",
    traits: [
      "commands arcane elements",
      "speaks in incantations",
      "sees magical auras",
      "fragile in melee",
    ],
    positiveKeywords: [
      "spell",
      "magic",
      "arcane",
      "rune",
      "incantation",
      "elemental",
      "fireball",
      "lightning",
      "ritual",
      "summon",
      "enchant",
      "mana",
    ],
    negativeKeywords: [
      "sword",
      "punch",
      "brawl",
      "tackle",
      "headbutt",
      "gun",
      "wrestle",
    ],
    personality:
      "Dramatic, verbose, and condescending toward mundane solutions. Loves theatrical spell names.",
    imagePath: "/characters/wizard.png",
  },
  {
    id: "knight",
    name: "knight",
    displayName: "Sir Galenhart",
    description:
      "An honorable knight bound by a chivalric code and clad in gleaming plate.",
    traits: [
      "master swordsman",
      "bound by honor",
      "unshakeable courage",
      "heavy and slow",
    ],
    positiveKeywords: [
      "sword",
      "shield",
      "honor",
      "duel",
      "charge",
      "lance",
      "valor",
      "parry",
      "oath",
      "protect",
      "joust",
      "armor",
    ],
    negativeKeywords: [
      "trick",
      "backstab",
      "lie",
      "ambush",
      "coward",
      "flee",
      "poison",
    ],
    personality:
      "Formal, earnest, and allergic to dishonorable tactics. Refers to foes as 'knave'.",
    imagePath: "/characters/knight.png",
  },
  {
    id: "gen-z",
    name: "gen-z",
    displayName: "Kai the Unbothered",
    description:
      "A chronically online zoomer whose memes bend reality and whose vibes are immaculate.",
    traits: [
      "weaponized irony",
      "meme manipulation",
      "viral presence",
      "short attention span",
    ],
    positiveKeywords: [
      "slay",
      "vibe",
      "rizz",
      "based",
      "meme",
      "tiktok",
      "viral",
      "cringe",
      "bet",
      "aura",
      "sigma",
      "lowkey",
      "fr",
    ],
    negativeKeywords: [
      "email",
      "fax",
      "cursive",
      "landline",
      "newspaper",
      "boomer",
    ],
    personality:
      "Ironic, detached, chronically online. Everything is either 'fire' or 'mid'.",
    imagePath: "/characters/gen-z.png",
  },
  {
    id: "monk",
    name: "monk",
    displayName: "Master Wu",
    description:
      "A serene martial artist whose fists move faster than thought.",
    traits: [
      "inner peace",
      "lightning reflexes",
      "channels chi",
      "refuses modern weapons",
    ],
    positiveKeywords: [
      "chi",
      "meditate",
      "balance",
      "focus",
      "palm",
      "kick",
      "harmony",
      "discipline",
      "breath",
      "stance",
      "pressure point",
    ],
    negativeKeywords: [
      "gun",
      "bomb",
      "rage",
      "greed",
      "cheat",
      "shortcut",
      "lazy",
    ],
    personality:
      "Calm, cryptic, speaks in koans and proverbs. Values discipline over flash.",
    imagePath: "/characters/monk.png",
  },
  {
    id: "time-traveler",
    name: "time-traveler",
    displayName: "Dr. Chronos",
    description:
      "A dimension-hopping scientist armed with a glitchy wristwatch that bends causality.",
    traits: [
      "manipulates time",
      "anachronistic gadgets",
      "predicts outcomes",
      "paradox-prone",
    ],
    positiveKeywords: [
      "rewind",
      "paradox",
      "future",
      "past",
      "loop",
      "timeline",
      "chrono",
      "predict",
      "dimension",
      "wristwatch",
      "causality",
    ],
    negativeKeywords: [
      "permanent",
      "static",
      "unchangeable",
      "slow",
      "stuck",
    ],
    personality:
      "Frantic, over-explanatory, drops names of historical figures as personal friends.",
    imagePath: "/characters/time-traveler.png",
  },
  {
    id: "archer",
    name: "archer",
    displayName: "Sylva Longshot",
    description:
      "A sharp-eyed forest ranger who never misses and whispers to the wind.",
    traits: [
      "impossible aim",
      "wind reading",
      "stealthy movement",
      "weak up close",
    ],
    positiveKeywords: [
      "bow",
      "arrow",
      "aim",
      "shot",
      "quiver",
      "target",
      "wind",
      "forest",
      "stealth",
      "snipe",
      "pierce",
      "feather",
    ],
    negativeKeywords: [
      "grapple",
      "hug",
      "melee",
      "wrestle",
      "close quarters",
      "brawl",
    ],
    personality:
      "Quiet, patient, and terse. Measures conversations in heartbeats between shots.",
    imagePath: "/characters/archer.png",
  },
  {
    id: "artist",
    name: "artist",
    displayName: "Vivi Brushstroke",
    description:
      "A temperamental painter whose canvases come to life when she's inspired.",
    traits: [
      "living paintings",
      "color manipulation",
      "dramatic flair",
      "fragile ego",
    ],
    positiveKeywords: [
      "paint",
      "canvas",
      "color",
      "brush",
      "palette",
      "masterpiece",
      "inspire",
      "muse",
      "portrait",
      "sculpt",
      "vision",
    ],
    negativeKeywords: [
      "boring",
      "gray",
      "plain",
      "corporate",
      "copy",
      "generic",
    ],
    personality:
      "Moody, flamboyant, takes everything personally. Demands a muse before acting.",
    imagePath: "/characters/artist.png",
  },
  {
    id: "boomer",
    name: "boomer",
    displayName: "Big Hank",
    description:
      "A retired dad whose lawnmower, cargo shorts, and life advice are all lethal.",
    traits: [
      "dad strength",
      "tool mastery",
      "unshakeable routine",
      "confused by tech",
    ],
    positiveKeywords: [
      "lawn",
      "mower",
      "grill",
      "wrench",
      "garage",
      "coupon",
      "dadjoke",
      "handshake",
      "newspaper",
      "sensible",
      "bootstraps",
    ],
    negativeKeywords: [
      "tiktok",
      "crypto",
      "meme",
      "emoji",
      "app",
      "wifi",
      "selfie",
    ],
    personality:
      "Gruff, nostalgic, lectures opponents about the price of gas in 1987.",
    imagePath: "/characters/boomer.png",
  },
  {
    id: "goblin",
    name: "goblin",
    displayName: "Grit the Gremlin",
    description:
      "A greedy little menace who hoards shinies and fights dirty.",
    traits: [
      "dirty tricks",
      "hoarder instincts",
      "small and quick",
      "easily distracted by gold",
    ],
    positiveKeywords: [
      "trap",
      "trick",
      "sneak",
      "bite",
      "shiny",
      "loot",
      "bomb",
      "cackle",
      "horde",
      "dagger",
      "scurry",
    ],
    negativeKeywords: [
      "honor",
      "noble",
      "share",
      "polite",
      "clean",
      "manners",
    ],
    personality:
      "Wheezy, cackling, greedy. Will abandon any fight for a gold coin.",
    imagePath: "/characters/goblin.png",
  },
  {
    id: "otaku",
    name: "otaku",
    displayName: "Senpai Akira",
    description:
      "An anime superfan whose belief in friendship powers literal super moves.",
    traits: [
      "power of friendship",
      "signature finishers",
      "encyclopedic trivia",
      "dramatic monologues",
    ],
    positiveKeywords: [
      "friendship",
      "nakama",
      "senpai",
      "kamehameha",
      "anime",
      "manga",
      "finisher",
      "transformation",
      "training arc",
      "sakura",
      "bankai",
    ],
    negativeKeywords: [
      "dub",
      "spoiler",
      "live action",
      "filler",
      "cancel",
    ],
    personality:
      "Over-the-top, shouts move names, monologues mid-battle about bonds and destiny.",
    imagePath: "/characters/otaku.png",
  },
  {
    id: "professor",
    name: "professor",
    displayName: "Prof. Lexington",
    description:
      "A tweed-clad academic whose footnotes are sharper than any blade.",
    traits: [
      "encyclopedic knowledge",
      "weaponized citations",
      "logical rigor",
      "physically unimpressive",
    ],
    positiveKeywords: [
      "theory",
      "logic",
      "citation",
      "thesis",
      "footnote",
      "research",
      "hypothesis",
      "axiom",
      "tenure",
      "lecture",
      "evidence",
    ],
    negativeKeywords: [
      "gut feeling",
      "vibes",
      "improvise",
      "yolo",
      "nonsense",
      "plagiarize",
    ],
    personality:
      "Pedantic, condescending, cites sources mid-fight. Corrects grammar of opponents.",
    imagePath: "/characters/professor.png",
  },
];

export function getCharacter(id: string): CharacterConfig | undefined {
  return CHARACTERS.find((c) => c.id === id);
}
